### ISSUE TITLE
Import error on trajectorama

### ISSUE THREAD

**Issue by TheInfamousWayne** [brianhie/trajectorama#6]
>>> import trajectorama
/usr/local/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/trajectorama/__init__.py", line 1, in <module>
    from .trajectorama import *
  File "/usr/local/lib/python3.7/site-packages/trajectorama/trajectorama.py", line 9, in <module>
    from .pan_dag import PanDAG
  File "/usr/local/lib/python3.7/site-packages/trajectorama/pan_dag.py", line 11, in <module>
    from ._louvain import louvain
  File "/usr/local/lib/python3.7/site-packages/trajectorama/_louvain.py", line 10, in <module>
    from scanpy import utils
ImportError: cannot import name 'utils' from 'scanpy' (/usr/local/lib/python3.7/site-packages/scanpy/__init__.py)
>>>

**Comment by brianhie** [comment]
Thanks for the issue! What version of scanpy are you using? The version in our tests (version `1.4.5`) seems to support `from scanpy import utils`.

**Comment by TheInfamousWayne** [comment]
Thanks. I'm working with python3. It works when I do the following:
`pip3 install scanpy==1.4.5`
