### ISSUE TITLE
import trajectorama fails on scanpy utils

### ISSUE THREAD

**Issue by emdann** [brianhie/trajectorama#8]
When running `import trajectorama` I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/emma_env/lib/python3.7/site-packages/trajectorama/__init__.py", line 1, in <module>
    from .trajectorama import *
  File "/home/jovyan/my-conda-envs/emma_env/lib/python3.7/site-packages/trajectorama/trajectorama.py", line 9, in <module>
    from .pan_dag import PanDAG
  File "/home/jovyan/my-conda-envs/emma_env/lib/python3.7/site-packages/trajectorama/pan_dag.py", line 11, in <module>
    from ._louvain import louvain
  File "/home/jovyan/my-conda-envs/emma_env/lib/python3.7/site-packages/trajectorama/_louvain.py", line 10, in <module>
    from scanpy import utils
ImportError: cannot import name 'utils' from 'scanpy' (/home/jovyan/my-conda-envs/emma_env/lib/python3.7/site-packages/scanpy/__init__.py)
```

Substituting `from scanpy import utils` with `from scanpy import _utils` in `trajectorama/trajectorama/_louvain.py` solves the issue.

```python
>>> scanpy.__version__
<Version('1.4.5.post3.dev17+g09b9856')>
```

**Comment by brianhie** [comment]
Thanks! Should be fixed in https://github.com/brianhie/trajectorama/pull/10
